##########################################################################################
# kubectl -n keycloak describe externalsecret keycloak-credentials # to check the status #
##########################################################################################
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: ke-xently
---
# This file defines how to fetch secrets from Google Secret Manager.
# It assumes a ClusterSecretStore named 'gcp-secret-store' is configured to
# point to your GCP project.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-credentials
  namespace: keycloak
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-credentials # Creates a K8s secret with this name
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_USERNAME
      remoteRef:
        key: keycloak-keycloak-admin-user
        version: "latest"
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: keycloak-keycloak-admin-password
        version: "latest"
    - secretKey: DB_USERNAME
      remoteRef:
        key: keycloak-keycloak-db-user
        version: "latest"
    - secretKey: DB_PASSWORD
      remoteRef:
        key: keycloak-keycloak-db-password
        version: "latest"