apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
  namespace: keycloak
spec:
  provider:
    gcpsm:
      projectId: ke-xently # TODO: set to your GCP project ID (or manage via Terraform/Helm)

# This file defines how to fetch secrets from Google Secret Manager.
# It assumes a ClusterSecretStore named 'gcp-secret-store' is configured to
# point to your GCP project.
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-credentials
  namespace: keycloak
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-credentials # Creates a K8s secret with this name
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_USERNAME
      remoteRef:
        key: keycloak-keycloak-admin-user
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: keycloak-keycloak-admin-password
    - secretKey: DB_USERNAME
      remoteRef:
        key: keycloak-keycloak-db-user # The name of the secret in GCP Secret Manager
    - secretKey: DB_PASSWORD
      remoteRef:
        key: keycloak-keycloak-db-password