apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit all resources from the base
resources:
  - ../../base
  # Add the development-specific secrets
  - secrets.yaml
  - services.yaml
  - configs.yaml
patches:
  - path: patch-resources.yaml