apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: keycloak
spec:
  template:
    spec:
      containers:
        - name: keycloak
          args: ["start-dev", "--import-realm"]
          env:
            # In this explorative setup, no strict hostname is set.
            # For production environments, set a hostname for a secure setup.
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME
              value: "http://keycloak.keycloak.svc.cluster.local:8080"
          #  - name: KC_HTTPS_CERTIFICATE_FILE
          #    value: "/opt/keycloak/conf/server.crt.pem"
          #  - name: KC_HTTPS_CERTIFICATE_KEY_FILE
          #    value: "/opt/keycloak/conf/server.key.pem"
          #startupProbe:
          #  httpGet:
          #    scheme: HTTPS
          #readinessProbe:
          #  httpGet:
          #    scheme: HTTPS
          #livenessProbe:
          #  httpGet:
          #    scheme: HTTPS
          volumeMounts:
            - name: dt-bank-keycloak-realm-volume
              mountPath: /opt/keycloak/data/import/
      volumes:
        - name: dt-bank-keycloak-realm-volume
          configMap:
            name: dt-bank-keycloak-realm-config
