apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db-pvc
  namespace: keycloak
spec:
  accessModes: [ "ReadWriteOnce" ] # This volume can be mounted by a single node
  resources:
    requests:
      storage: 1Gi # Adjust size as needed