apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-database
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-database
  template:
    metadata:
      labels:
        app: keycloak-database
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - name: keycloak-svc-db
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "authentication"
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: keycloak-credentials, key: DB_USERNAME } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: keycloak-credentials, key: DB_PASSWORD } }
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe: # K8s equivalent of healthcheck
            exec:
              command: [ "pg_isready", "-U", "test", "-d", "authentication" ]
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: keycloak-db-pvc
