apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: keycloak
spec:
  template:
    spec:
      containers:
        - name: keycloak
          args: ["start-dev", "--import-realm"]
          env:
            # In this explorative setup, no strict hostname is set.
            # For production environments, set a hostname for a secure setup.
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME
              value: "https://keycloak.keycloak.svc.cluster.local"
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: "/opt/keycloak/conf/server.crt.pem"
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: "/opt/keycloak/conf/server.key.pem"