apiVersion: v1
kind: Service
metadata:
  name: keycloak-loadbalancer
  namespace: keycloak
spec:
  selector:
    app: keycloak
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: keycloak-http
    - name: https
      protocol: TCP
      port: 8443
      targetPort: keycloak-https