apiVersion: v1
kind: Service
metadata:
  name: keycloak-database
  namespace: keycloak
spec:
  selector:
    app: keycloak-database
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: keycloak-svc-db