apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  type: ClusterIP # Expose internally first. Use an Ingress for external access.
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: keycloak-http
    - name: https
      protocol: TCP
      port: 8443
      targetPort: keycloak-https
    - name: mgmt
      protocol: TCP
      port: 9000
      targetPort: keycloak-mgmt
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-discovery
  namespace: keycloak
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  # Allow not-yet-ready Pods to be visible to ensure the forming of a cluster if Pods come up concurrently
  publishNotReadyAddresses: true
  clusterIP: None
  type: ClusterIP