apiVersion: apps/v1
# Use a stateful setup to ensure that for a rolling update Pods are restarted with a rolling strategy one-by-one.
# This prevents losing in-memory information stored redundantly in two Pods.
kind: StatefulSet
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  serviceName: keycloak-discovery
  volumeClaimTemplates:
    - metadata:
        name: keycloak-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: "ghcr.io/xently/keycloak:26.3.1"
          args: ["start", "--optimized", "--proxy-headers", "xforwarded"]
          ports:
            - name: keycloak-http
              containerPort: 8080
            - name: keycloak-https
              containerPort: 8443
            - name: keycloak-mgmt
              containerPort: 9000
          env:
            # This allows Keycloak to be accessed via HTTP, which is common
            # inside a cluster where a separate Ingress handles TLS termination.
            - name: KC_HTTP_ENABLED
              value: "true"
            #- name: KC_HTTP_MANAGEMENT_ENABLED
            #  value: "true"
            - name: KC_CACHE
              value: "ispn"
            # Passing the Pod's IP primary address to the JGroups clustering as this is required in IPv6 only setups
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KC_DB_URL
              value: "jdbc:postgresql://keycloak-database.keycloak.svc.cluster.local:5432/authentication"
            - name: KC_DB_USERNAME
              valueFrom: { secretKeyRef: { name: keycloak-credentials, key: DB_USERNAME } }
            - name: KC_DB_PASSWORD
              valueFrom: { secretKeyRef: { name: keycloak-credentials, key: DB_PASSWORD } }
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom: { secretKeyRef: { name: keycloak-credentials, key: ADMIN_USERNAME } }
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom: { secretKeyRef: { name: keycloak-credentials, key: ADMIN_PASSWORD } }
          volumeMounts:
            - name: keycloak-storage
              mountPath: /opt/keycloak/data
          startupProbe:
            httpGet:
              scheme: HTTP
              path: /health/started
              port: 9000
            periodSeconds: 2
            failureThreshold: 300
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health/ready
              port: 9000
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health/live
              port: 9000
            periodSeconds: 10
            failureThreshold: 3