name: Teardown

on:
  workflow_dispatch:
    inputs:
      confirm_k8s:
        description: "Type DELETE to confirm deletion of Kubernetes resources"
        required: true
        default: "Kubernetes"
      confirm_infra:
        description: "Type DELETE to confirm deletion of Terraform resources"
        required: true
        default: "Terraform"
      remove_namespaces:
        description: "Also delete namespaces (keycloak, external-secrets, ingress-nginx, cert-manager). WARNING: This will remove all objects including PVCs in those namespaces."
        required: false
        default: "false"
      remove_crds:
        description: "Also delete External Secrets CRDs (cluster-scoped). Usually not necessary."
        required: false
        default: "false"
      remove_cert_manager_crds:
        description: "Also delete cert-manager CRDs (cluster-scoped). Only if you are sure nothing else depends on cert-manager."
        required: false
        default: "false"

permissions:
  contents: read
  id-token: write

jobs:
  destroy-k8s:
    name: Delete Kubernetes resources on GKE
    runs-on: ubuntu-24.04
    if: github.event.inputs.confirm_k8s == 'DELETE'
    defaults:
      run:
        shell: bash
        working-directory: ops/k8s/overlays/production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GKE access (OIDC + gcloud + kubeconfig + Helm)
        uses: ./.github/actions/gke-setup
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Delete production overlay resources
        run: |
          set -euo pipefail
          # Delete the overlay resources (namespace-scoped)
          kubectl delete -k . --ignore-not-found=true || true

      - name: Uninstall External Secrets (Helm)
        run: |
          set -euo pipefail
          # Uninstall the Helm release if present
          if helm status external-secrets -n external-secrets >/dev/null 2>&1; then
            helm uninstall external-secrets -n external-secrets || true
          fi

      - name: Uninstall cert-manager (Helm)
        run: |
          set -euo pipefail
          if helm status cert-manager -n cert-manager >/dev/null 2>&1; then
            helm uninstall cert-manager -n cert-manager || true
          fi

      - name: Uninstall NGINX Ingress Controller (Helm)
        run: |
          set -euo pipefail
          if helm status ingress-nginx -n ingress-nginx >/dev/null 2>&1; then
            helm uninstall ingress-nginx -n ingress-nginx || true
          fi

      - name: Optional - Delete namespaces (DANGEROUS)
        if: ${{ github.event.inputs.remove_namespaces == 'true' }}
        run: |
          set -euo pipefail
          for ns in keycloak external-secrets ingress-nginx cert-manager; do
            if kubectl get ns "$ns" >/dev/null 2>&1; then
              echo "Deleting namespace $ns (this will remove all objects including PVCs)"
              kubectl delete ns "$ns" --ignore-not-found=true --wait=true || true
            fi
          done

      - name: Optional - Delete External Secrets CRDs (cluster-scoped)
        if: ${{ github.event.inputs.remove_crds == 'true' }}
        run: |
          set -euo pipefail
          # These are cluster-scoped CRDs; remove only if you are sure no other namespaces use ESO
          for crd in externalsecrets.external-secrets.io clustersecretstores.external-secrets.io secretstores.external-secrets.io; do
            kubectl delete crd "$crd" --ignore-not-found=true || true
          done

      - name: Optional - Delete cert-manager CRDs (cluster-scoped)
        if: ${{ github.event.inputs.remove_cert_manager_crds == 'true' }}
        run: |
          set -euo pipefail
          # cert-manager CRDs are cluster-scoped and shared; remove only if you are sure nothing else depends on it
          for crd in certificates.cert-manager.io certificaterequests.cert-manager.io challenges.acme.cert-manager.io clusterissuers.cert-manager.io issuers.cert-manager.io orders.acme.cert-manager.io; do
            kubectl delete crd "$crd" --ignore-not-found=true || true
          done

      - name: Summary
        run: |
          echo "Teardown complete. If namespaces were not deleted, some PVCs may remain; delete them manually if needed."

  destroy-infra:
    name: Terraform destroy (GCP infra)
    needs:
      - destroy-k8s
    runs-on: ubuntu-24.04
    if: github.event.inputs.confirm_infra == 'DELETE'
    defaults:
      run:
        shell: bash
        working-directory: ops/terraform
    env:
      TF_IN_AUTOMATION: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
